Integration/adhvik/acm 9 aws
AWV2804/461_Phase2 pull request #1
Opened 2024-10-20 21:01 UTC by adhvik-kannan

2024-10-20 22:26 UTC, nsykim requested changes

2024-10-20 22:26 UTC, nsykim commented on src/database_test.ts
> +    score: String,
should we have this as a [string] ? that way we don't have to do any decoding to parse the output

2024-10-20 22:26 UTC, nsykim commented on src/database_test.ts
> +// Define a schema
make sure to add the docstring

2024-10-20 22:26 UTC, nsykim commented on src/database_test.ts
> +export async function addNewPackage(name: String, url: String, score?: String, version?: String, previousVersion?: String) {
should version be optional? even if we don't want to ingest, doesn't it make sense to store the version number? not sure how we would handle it if they add the same package but with different versions without ingesting, though.

2024-10-20 22:26 UTC, nsykim commented on src/database_test.ts
> +        console.error('Error saving package:', error);
will need to return an error so that API can return error to frontend to display. please do this for all instances of try catch blocks

2024-10-20 22:26 UTC, nsykim commented on src/database_test.ts
> +export async function updatePackageVersion(name: string, newVersion: string) {
doesn't it make sense to merge this function with the update score function? if we are updating the package score, are we necessarily ingesting? if we are, then we should merge them, because we will have to update the metric score either way.

2024-10-20 22:26 UTC, nsykim commented on src/database_test.ts
> +            console.log('Package not found');
give output if not found please

2024-10-21 21:13 UTC, adhvik-kannan commented on src/database_test.ts
> +export async function updatePackageVersion(name: string, newVersion: string) {
It's two function calls that do different things, so I do not want to combine them. It's really not that big of a deal to call two functions. I'm also assuming that rating will be done at a different time. Especially because at later times, when packages are uploaded, we don't need to come back and update the score, only need to update version

2024-10-24 21:23 UTC, closed without merging